apiVersion: v1
kind: Service
metadata:
  name: hello-python-service
  namespace: hello-python-test
spec:
  selector:
    app: hello-python
  ports:
  - protocol: "http"
    port: 6000
    targetPort: 5000
  type: ClusterIP
